### PR TITLE
Update Kotlin to 2.0.0

### PR DESCRIPTION
**Pull request by shoheikawano**
## What's changed?

I have updated Kotlin version from 1.9.23 to 2.0.0 and some other libraries to the latest version so that it works with the project with Kotlin 2.0 dependency.

## Why is this change necessary?

I faced the issue where my app crashes after I started using the library with Kotlin 2.0.0 in my project.

## What has been checked?

- I have checked if the sample project can be build successfully.
- I have checked that when clicking the Google Auth button it shows the dialog to let users choose their account to sign in.

### CODE REVIEW

**Comment by shoheikawano** [comment]
hopefully it closes this issue: https://github.com/mirzemehdi/KMPAuth/issues/24

**Comment by mirzemehdi** [comment]
Thank you very much for this implementation @shoheikawano. Overall, it looks good to me. But what is the reason to add 

`alias(libs.plugins.composeCompiler)` in gradle files? Is this required thing now?

**Comment by shoheikawano** [comment]
Hi @mirzemehdi thanks for checking.

> what is the reason to add alias(libs.plugins.composeCompiler) in gradle files? Is this required thing now?

Yes it is now required otherwise compilations fail

ref: https://www.jetbrains.com/help/kotlin-multiplatform-dev/compose-compiler.html#migrating-a-compose-multiplatform-project

**Review by mirzemehdi — APPROVED** [review]
Perfect!

**Pull request merged**
